### PR TITLE
Capture array commands

### LINKED ISSUE #8: Faking commands passed as array is not possible
A command passed as array is impossible to fake, because arrays aren't valid array keys.

E.g.:
```
Terminal::fake(["id '-u'" => '1000']);
Terminal::run(['id', '-u']); // Raises warning: 'Illegal offset type'
```

### PR DESCRIPTION
**Pull request by TitasGailius**
Fixes https://github.com/TitasGailius/terminal/issues/8

```php
Terminal::fake(["id '-u'" => '1000']);

Terminal::run(['id', '-u']); // Raises warning: 'Illegal offset type'
```

With this PR you could do this:

```php
Terminal::fake([
    'rm -rf vendor' => 'success',
]);

Terminal::run(['rm', '-rf', 'vendor']);

Terminal::assertExecuted('rm -rf vendor');
```

### CODE REVIEW

**Comment by paneidos** [comment]
This seems to do the trick. I was thinking about using escapeshellarg/escapeshellcmd or not to handle arguments with spaces. It would make setting up the fakes a little more complex, but would be more correct.

**Comment by paneidos** [comment]
Code with `escapeshellcmd`/`escapeshellarg` could look like this:
```
if (is_array($this->command) {
    $cmd = escapeshellcmd($this->command[0]);
    $args = array_map('escapeshellarg', array_slice($this->command, 1));
    return $cmd . ' ' . implode(' ', $args);
}
```

Because the result of these escape functions is platform-dependent, I was also thinking about extracting it into a static method, so you can use it in your tests like this:
```
Terminal::fake([
  Terminal::commandLine(['rm', '-rf', 'vendor']) => 'success',
]);
```

**Comment by TitasGailius** [comment]
I have mixed feelings about this.

The main purpose of faking a command is to allow your app to run without actually executing it. Additionally, you may assert that the command was "executed" and test how the app behaves with different responses.

Which makes it irrelevant how the command is converted to the string because the command is never actually executed.

If you wanted to test how the command is prepared for different platforms, that's a different thing. You could do something like this:
```php
// Get an instance of the Symfony Process class which has `getCommandLine` method.
$process = Terminal::command(['rm', '-rf', 'vendor'])->process();

$this->assertEquals(..., $process->getCommandLine());
```
---
**On the other hand**, I agree that it would be much nicer to pass the same variable when faking, executing and asserting the command.

**Comment by paneidos** [comment]
Escaping arguments would also prevent any trouble with spaces in arguments. Even though the chances of someone running into a such problem should be slim, it's better to prevent them.

**Comment by TitasGailius** [comment]
ok, so I've created a `Terminal::toString` method which converts a given command to a string.
Which makes it possible to properly fake array commands:

```php
$command = ['rm', '-rf', 'vendor'];

Terminal::fake([
    Terminal::toString($command) => 'success',
]);

$response = Terminal::run($command);

Terminal::assertExecuted($command);

$this->assertEquals('success', $response->output());
```

**Comment by TitasGailius** [comment]
I will probably merge this tomorrow.

**Comment by paneidos** [comment]
Looks good to me. Thank you very much for the quick response and implementation!

**Pull request merged**
